business_name:
  default: "MyIT CRM  Software Company"
business_slogan:
  default: "The Best CRM Software for your Repair Shop"
business_phone:
  default: '02 9999 8888'
business_toll_free:
  default: '02 9999 8888'
business_fax:
  default: '02 9999 8888'
business_mobile:
  default: '02 9999 8888'
business_email:
  default: "admin@exmaple.com"
technician_email:
  default: "curt@ii-inc.ca"
no_reply_email:
  default: "noreply@ii-inc.ca"
accountant_email:
  default: "ross@ii-inc.ca"
service_email:
  default: "service@ii-inc.ca"
business_address:
  default: ''
business_city:
  default: 'Edmonton'
business_state:
  default: 'Alberta'
business_zip_code:
  default: ''
business_country:
  default: 'Canada'
business_number:
  default: ''
meta_tags:
  default: 'CRM, FREE, Opensource, Repair, Business, Computer, IT, Shop'
tax_type:
  default: 'GST'
tax_rate:
  default: '10'
logout_limit:
  default: 'true'
idle_time:
  default: '10'
version:
  default: 'v2.0.0'
default_invoice_note:
  default: 'Thankyou for your support and Business. All work is Guaranteed for up to 14 days from date of completion.'
default_invoice_terms:
  default: '25,50,100'




